\input texinfo
@c This top-level file is so trivial, it has to be public domain.
@settitle Perl Pod documentation
@finalout
@tex
\global\hfuzz=\maxdimen
\global\hbadness=10000
@end tex

@titlepage
@title Perl documentation in Texinfo
@end titlepage

@shortcontents
@contents

@node Top
@top Perl pod documentation

This translation of the Perl documentation
(@url{http://perldoc.perl.org}) from Pod to Texinfo is not official,
and not endorsed by the Perl developers (indeed, they haven't seen
it).  It was created by the GNU Texinfo developers because they found
it useful to have the Perl documentation available in Info and other
formats, and thought they would share the results.  Suggestions welcome.

This is created entirely by the Texinfo tools; see the
@url{https://cgit.git.savannah.gnu.org/cgit/texinfo.git/tree/contrib/perldoc-all,
@file{contrib/perldoc-all}} directory in the Texinfo sources for the
procedure used.
@c  The output is available at
@c @url{http://www.gnu.org/software/perl/manual}.

@include perldoc-all-incl.texi

@bye
