# input_dir_non_ascii_native.sh generated by ./../../maintain/generate_many_input_files_native_tests.sh.
#
# Copyright Free Software Foundation, Inc.
#
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without
# modifications, as long as this notice is preserved.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[ "z$srcdir" = 'z' ] && srcdir=.

$srcdir/input_dir_non_ascii.sh -native

