#!/bin/sh
# Texinfo's wrapper for the Gnulib script config/srclist-update,
# to define particular variables our srclist.txt uses.
# 
# Copyright 2013-2023 Free Software Foundation, Inc.
#
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without
# modifications, as long as this notice is preserved.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# per-user overrides.
case $LOGNAME in
karl)
  : ${GNULIB=$HOME/gnu/src/gnulib};                 export GNULIB
  ;;
g)
  : ${GNULIB=$HOME/src/texinfo/gnulib} ; export GNULIB
esac

mydir=`dirname $0`
(cd "$mydir/.." && $GNULIB/config/srclist-update <util/srclist.txt) \
| sed 's/^## /cp /'
