#!/usr/bin/env perl
# Copyright 2012-2025 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Original author: Patrice Dumas.
#
# Output Texinfo customization variables

use strict;

BEGIN {
  (my $mydir = $0) =~ s,/[^/]+$,,;
  chomp (my $tpdir = `cd $mydir/../tp && pwd`);
  unshift (@INC, $tpdir);
  if (defined($ENV{'top_builddir'})) {
    unshift (@INC, $ENV{'top_builddir'}.'/tp');
  }

  $ENV{top_srcdir} = "$tpdir/..";
  require Texinfo::ModulePath;
  Texinfo::ModulePath::init(undef, undef, undef);
}

use Texinfo::Options;
use Texinfo::Common;

my $do_customization_variable_commands = $ARGV[0] eq "--commands";

if ($do_customization_variable_commands) {
  print join("\n",
          sort(keys(%Texinfo::Options::multiple_at_command_options),
               keys(%Texinfo::Options::unique_at_command_options)));
  exit 0;
}

my %parser_customization = %Texinfo::Options::parser_options;

# avoid commands by selecting only upper cased customization variables
# also remove array and hash references
my @parser_string_non_command_customization
    = grep {ref($parser_customization{$_}) eq '' and $_ =~ /^[A-Z0-9_]+$/ }
              keys(%parser_customization);

print join("\n",
     sort(@parser_string_non_command_customization,
          keys(%Texinfo::Options::program_cmdline_options),
          keys(%Texinfo::Options::converter_cmdline_options),
          keys(%Texinfo::Options::program_customization_options),
          keys(%Texinfo::Options::converter_customization_options)));
