\input texinfo   @c -*-texinfo-*-
@c vim: filetype=texinfo tabstop=4 shiftwidth=4
@c %**start of header (This is for running Texinfo on a region.)
@setfilename ti.info
@settitle Texindex: A program for sorting indices
@c %**end of header (This is for running Texinfo on a region.)

@c Merge the function and variable indexes into the concept index,
@c but without the code font; in the index entries we'll do the
@c font management ourselves.  Also merge in the chunk definition
@c and reference entries, which jrweave creates for us.
@c (Ordinarily this would be in the header, but jrweave puts the
@c defindexes later.)
@synindex fn cp
@synindex vr cp
@synindex cd cp
@synindex cr cp

@ifnottex
@ifnotdocbook
@macro ii{text}
@i{\text\}
@end macro
@end ifnotdocbook
@end ifnottex

@ifdocbook
@macro ii{text}
@inlineraw{docbook,<lineannotation>\text\</lineannotation>}
@end macro
@end ifdocbook

@copying
Copyright @copyright{} 2014-2026 Free Software Foundation, Inc.

@quotation
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see @url{https://www.gnu.org/licenses/}.
@end quotation
@end copying

@titlepage
@title Texindex
@author Arnold D. Robbins
@author and Texinfo maintainers
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top Texindex

This file was formerly the ``literate''  source of the @command{texindex}
program, an @code{awk} program that processes the raw index files produced
by the @file{texinfo.tex} file.

@command{texindex} is no longer maintained as a literate program.  This
file still contains some introductory sections and some test cases.

@end ifnottex

@node Preface
@nodedescription Introductory remarks.
@unnumbered Preface

This file describes @file{texindex.awk}, a reimplementation of the C
program @file{texindex.c}.  The purpose is to make the program more
maintainable.  As a practical benefit, it also supports correct sorting
and initials for the @samp{@{} and @samp{@}} characters in an index,
and multi-level index entries.
@cindex @{ (left brace), example index entry for
@cindex @} (right brace), example index entry for

@cindex TexiWeb Jr.@: literate programming system
@cindex Texinfo document formatting language
This was a @dfn{literate program}, written using the
@uref{https://github.com/arnoldrobbins/texiwebjr, @sc{TexiWeb Jr.@:}
literate programming system}.  The underlying documentation system is
@uref{https://www.gnu.org/software/texinfo, Texinfo}, the GNU
documentation formatting language.  A single source file produces the
runnable program, a printable document, and an online document.

@subheading Intended Audience

You should read this if you want to understand how @file{texindex.awk}
works.  You should be familiar with the @command{awk} programming
language.

If you are interested in array indexing, you've come to
the wrong place.  @xref{knuth}.

@c Scale figure to 4.5 inches which is good for both smallbook
@c and regular.  TeX will scale height also automatically.
@float Figure,knuth
@caption{Indexing (@url{https://xkcd.com/163/})}
@center @image{dek_idx, 5in, , Indexing}
@end float

@subheading Development History

This program was originally written in 2014 in order to enable
using left and right braces in index entries, and to provide a program
that would be more easily maintainable going forward than the C version.

In 2019, discussions on the Texinfo bug mailing list around adding
multi-level indexing and ``see'' and ``see also'' entries motivated
reworking the program.

In 2026, @command{texindex} ceased to be a literate program.  Going
forward, it will be maintained as an @command{awk} program only.

@node Requirements
@nodedescription How the program needs to work.
@chapter Requirements

The input to this program is the list of unsorted index entries produced
by @file{texinfo.tex} when a Texinfo document is processed.
This chapter presents the input to the program, the Texinfo
commands that produce that input, and the expected output from
this program.  It also presents some additional notes concerning
the requirements.

@node Desired printed output
@nodedescription What a printed index should look like.
@section Where We're Going

Let's first look at the kind of output desired.
A high-quality index has
several types of entries:

@table @asis
@item Single level entries
These are the most common; each entry has text and a list of one
or more page numbers.

@item Double level entries
These entries have subtopics; the top level entry may also have a
page number, or it may not.

@item Triple level entries
These entries have subtopics for the subtopics; the top level
and secondary entries may also have
page numbers, or they may not.

@item ``See @dots{}'' entries
Entries that point at other entries in the index, generally without
any subtopics. ``See'' entries do not have a page number of their own.

@item ``See also @dots{}'' entries
Entries that point at other entries, but often do have
subsequent direct page references of their own.
``See also'' entries are merged with regular entries,
their text coming after the page numbers.
@end table

Here's what they might look like when printed
(apologies in advance
for the use of a constant-width font):

@example
coffee makers . . . . . . . . . . 15         @ii{Single level entry}
       electric . . . . . . . 17, 22         @ii{Double level entry}
             blue . . . . . . . . 42         @ii{Triple level entry}
             pink . . . . . . . . 35         @ii{Another triple level entry}
@end example

The same hierarchy might appear without page numbers:

@example
coffee makers,                               @ii{Single level entry}
       electric,                             @ii{Double level entry}
             blue . . . . . . . . . . 42     @ii{Triple level entry}
             pink . . . . . . . . . . 35     @ii{Another triple level entry}
@end example

A ``See'' entry doesn't have page numbers:

@example
espresso makers, @ii{See} coffee makers
toasters, . . . . . . . . 42, @ii{See also} coffee makers
@end example

@node Texinfo indexing commands
@nodedescription How to write indexing commands.
@section Texinfo Indexing Commands

Texinfo provides a number of different commands for putting entries
into different indices.  For discussion we use the @code{@@cindex}
command in the following examples.  Of interest to @file{texindex.awk}
is the text of the one-to-three parts of an entry, and how the index
should be sorted.  Some examples:

@example
@@cindex coffee makers                                    @ii{One level}
@@cindex coffee makers @@subentry electric                 @ii{Tow levels}
@@cindex coffee makers @@subentry electric @@subentry blue  @ii{Three levels}
@end example

Here, the @code{@@subentry} separates the secondary and tertiary parts of
the entry from the primary part.

Additionally, each part may have an @code{@@sortas} clause:

@example
@@cindex coffee makers @@sortas@{Coffee Makers@}
@end example

``See'' and ``See also'' entries look like this:

@example
@@cindex espresso makers @@seeentry@{coffee makers@}
@@cindex toasters @@seealso@{coffee makers@}
@end example

@noindent
Note that there is (or should be) no comma between the primary text and the @code{@@seeentry}
or @code{@@seealso}: @file{texindex.awk} supplies a comma in the final
printed entry.

@node Input form
@nodedescription The input to @file{texindex.awk}.
@section Input To The Program

The output from @file{texinfo.tex} contains the data for the
different kinds of index entries described in the previous
section.  Each line is an @dfn{entry}. Each entry has from three
to five fields, where the first three fields represent the same
data for all entries.  Entries look as follows:

@example
@@entry@{@var{sortkey}@}@{@var{page or see}@}@{@var{primary}@}
@@entry@{@var{sortkey}@}@{@var{page or see}@}@{@var{primary}@}@{@var{secondary}@}
@@entry@{@var{sortkey}@}@{@var{page or see}@}@{@var{primary}@}@{@var{secondary}@}@{@var{tertiary}@}
@end example

The braces are balanced in all cases, although for use by this program,
literal braces (not necessarily balanced) can be included in the sort
key by escaping them with the @dfn{command character}.

@cindex backslash vs.@: at
@cindex command character, @samp{\} vs.@: @samp{@@}
In the example above, the command character is @samp{@@} (as in Texinfo
itself).  Historically, however, the command character was backslash
(@samp{\}), and @file{texindex.awk} can handle either one.
@file{texinfo.tex} switched to @samp{@@} as its command character in
index files in Texinfo 7.2, released in 2023.  The command character is
determined at run time by looking at the first character on the first
line of each input file.

The fields are as follows:

@table @var
@item sortkey
The text to use for sorting index entries.
Generally, this is the text of the line with all markup removed.
When an @code{@@sortas} clause is provided, its contents are used instead.
This field should contain only ASCII characters.

When there are subentries, the sort key is the concatenation of three
fields (or their sort @code{@@sortas} clauses), separated by
@code{@@subentry} and a space. @file{texindex.awk} needs to recognize
where there are multiple sort keys in order to print entries appropriately.

@item page or see
Either a page number (as a roman numeral or an integer, possibly
with additional markup), or an indication that that this is a ``See''
or ``See also'' entry.

@item primary
The primary text of the index entry.

@item secondary
The (optional) secondary text of the index entry.

@item tertiary
The (optional) tertiary text of the index entry.
@end table

Our mission (which we choose to accept) is to read the above input,
sort it appropriately, and produce the correct output.

@node Output form
@nodedescription The output from @file{texindex.awk}.
@section What The Output Should Look Like

Output consists four different commands, derived from the indexing input.
The middle two can have a variant where there is no page number.

@example
@@initial @{A@}                        @ii{For the initial over each group}

@@entry@{@var{indexing text}@}@{@var{pagenum}@}      @ii{Primary entry}
@@entry@{@var{indexing text}@}@{@}             @ii{Primary entry without page number}

@@secondary@{@var{indexing text}@}@{@var{pagenum}@}  @ii{Secondary entry}
@@secondary@{@var{indexing text}@}@{@}         @ii{Secondary entry without page number}

@@tertiary@{@var{indexing text}@}@{@var{pagenum}@}   @ii{Tertiary entry}
@end example

The commands are:

@table @code
@item @@initial
Besides the index entries,
@file{texindex.awk} must output special lines indicating the
first character (the @dfn{initial}) of keys grouped together, but only
if there is more than one initial used throughout the input file.

@item @@entry
This is for a plain index entry, or for the primary term in a multi-level
index entry.  When the primary appears only with a secondary entry,
there won't be a page number.

No page number is printed when there
is an @code{@@seeentry} in the entry. In that case,
the output from @file{texindex.awk} should be a combination of
the original input fields three and two.

@item @@secondary
This is for a secondary index entry in a multi-level index entry (i.e.
a subentry).  In the printed index output, these appear after a primary
index entry, and are indented.  When the secondary appears only with a
tertiary entry, there won't be a page number.

@item @@tertiary
This is for a tertiary index entry in a multi-level
index entry.  This one always has a page number, unless it is
a ``see'' entry.
@end table


@node Processing
@nodedescription Processing the data.
@section Processing Index Entries

The job is to sort the entries, and merge those which are identical
except for the page numbers.
The sorting should be in the order of: all symbols first, then all
digits, then all letters, with uppercase letters following lowercase
ones, so we will need some smarts.

Once sorted, the lines must be output in the correct form, depending
upon how many entries and subentries they have.

Input lines might be duplicated (same entry, same page, more than once),
so we will have to deal with that.

@node Assumptions
@nodedescription Additional assumptions.
@section Assumptions About Our Data

We make two fundamental assumptions:

@enumerate 1
@item
If a given sort key has more than one display text, we only take the
first (this matches the behavior of C @command{texindex}).  Put another
way, if the same sort key has two different display texts, it means that
different markup was used, probably inadvertently, and we just take the
first.  As an example, consider these two Texinfo commands:

@example
@@cindex @@file@{field_split()@} function
@dots{}
@@cindex @@code@{field_split()@} function
@end example

@noindent
They produce the following output via @file{texinfo.tex},
which in turn is the input to @file{texindex.awk}:

@example
@@entry@{field_split() function@}@{2@}@{@@file @{field_split()@} function@}
@@entry@{field_split() function@}@{7@}@{@@code @{field_split()@} function@}
@end example

@noindent
The result will be a single entry, using @code{@@file},
accumulating the page numbers:

@example
@@entry@{@@file @{field_split()@} function@}@{2, 7@}
@end example

However, this poses a problem for the use of accented characters.
@file{texinfo.tex} should only output characters in the ASCII range
(0-127) in sort keys in its index files, as it is not possible to reliably
process these with an awk program in a portable and locale-independent
way.  This means that when words differ only by accents (as with the German
words ``Bogen'' and ``Bögen''), they may in fact have the same sort key,
but should not be merged.

@item
@cindex roman numerals
For the same sort key and text, page numbers will be monotonically
increasing.  This means we can just use a new page number when it comes
in, and not have to sort entries based on both sort key and page number.
In turn, this means that we don't need to worry about page numbers
that are roman numerals (which can occur).

@end enumerate

@node Portability
@nodedescription Using portable @command{awk}.
@section Using Portable @command{awk}

An additional requirement, for ease of deployment, is that the program
be written in portable @command{awk}, and not use features found only in
GNU @command{awk} (@command{gawk}).  For our purposes, ``portable''
means ``new'' @command{awk} as defined in the 1988 book by Aho,
Weinberger and Kernighan.  This gives us functions, multidimensional
arrays and a number of other important features over the original
@command{awk} shipped with V7 Unix.

In practice, we can also rely on basic features added in POSIX
@command{awk} should we need to (such as @code{CONVFMT}), although
at the moment there are no such features used by @file{texindex.awk}.

We tested the program with five versions of @command{awk} (@command{gawk},
@command{mawk}, Brian Kernighan's @command{awk}, @command{goawk},
and Busybox @command{awk}) on a large index and got byte-identical
results from all five.

@node Test Cases
@nodedescription Test index entries
@chapter Test index entries

@cindex test case @seeentry{testing}
@cindex test case @seeentry{brief case}
@cindex coffee
@cindex coffee @seealso{tea}
@cindex coffee @seealso{coca-cola}
@cindex whisky @seealso{soda}
@cindex whisky @seealso{scotch}


Here are some test cases:

@c These should make a nice test case!
@cindex coffee makers

@cindex toasters @subentry british
@cindex toasters @subentry american

@cindex microwaves @subentry electric @subentry 110 volt
@cindex microwaves @subentry electric @subentry 220 volt

@cindex children
@cindex children @subentry small
@cindex children @subentry small @subentry toddlers
@cindex children @subentry small @subentry infants
@cindex children @subentry teenagers
@cindex children @subentry adult
@example
@@c Top level entry, with page
@@cindex coffee makers

@@c Double level, no separate top level
@@cindex toasters @@subentry british
@@cindex toasters @@subentry american

@@c Triple level, no separate 1st or 2nd level
@@cindex microwaves @@subentry electric @@subentry 110 volt
@@cindex microwaves @@subentry electric @@subentry 220 volt

@@c All 3 levels, with pages
@@cindex children
@@cindex children @@subentry small
@@cindex children @@subentry small @@subentry toddlers
@@cindex children @@subentry small @@subentry infants
@@cindex children @@subentry teenagers
@@cindex children @@subentry adult

@@c More examples
@@cindex test case @@seeentry@{testing@}
@@cindex test case @@seeentry@{brief case@}
@@cindex coffee
@@cindex coffee @@seealso@{tea@}
@@cindex coffee @@seealso@{coca-cola@}
@@cindex whisky @@seealso@{soda@}
@@cindex whisky @@seealso@{scotch@}
@end example

@noindent
@xref{Index}, to see if the above test cases are handled properly.

@node Index
@nodedescription Combined index.
@unnumbered Index

@printindex cp

@bye
