#! /bin/sh
# generate_many_input_files_native_tests.sh: for each script in argument,
# generate a wrapper calling the script with -native argument.

# Copyright 2012-2026 Free Software Foundation, Inc.
#
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without
# modifications, as long as this notice is preserved.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# called through many_input_files Makefile:
#  cd tests/many_input_files
#  make native_test_scripts_target

[ "z$srcdir" = 'z' ] && srcdir=.

for file in "$@" ; do
  bfile=`basename $file .sh`
  basefile=${bfile}_native.sh
  outfile=${srcdir}/$basefile
  echo "doing $outfile" 1>&2
  cat >$outfile <<END_HEADER
# $basefile generated by $0.
#
# Copyright Free Software Foundation, Inc.
#
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without
# modifications, as long as this notice is preserved.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[ "z\$srcdir" = 'z' ] && srcdir=.

\$srcdir/$bfile.sh -native

END_HEADER
  chmod a+x $outfile
done
