/* ANSI-C code produced by gperf version 3.3 */
/* Command-line: gperf --output-file=C/main/txi_documentlanguage_scripts.c -N txi_in_language_scripts maintain/documentlanguage/scripts.gperf  */
/* Computed positions: -k'1-4' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
#error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gperf@gnu.org>."
#endif

#line 1 "maintain/documentlanguage/scripts.gperf"

#include <config.h>
#include <string.h>

#define TOTAL_KEYWORDS 224
#define MIN_WORD_LENGTH 4
#define MAX_WORD_LENGTH 4
#define MIN_HASH_VALUE 10
#define MAX_HASH_VALUE 649
/* maximum key range = 640, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
/*ARGSUSED*/
static unsigned int
hash (register const char *str, register size_t len)
{
  static unsigned short asso_values[] =
    {
      650, 650, 650, 650, 650, 650, 650, 650, 650, 650,
      650, 650, 650, 650, 650, 650, 650, 650, 650, 650,
      650, 650, 650, 650, 650, 650, 650, 650, 650, 650,
      650, 650, 650, 650, 650, 650, 650, 650, 650, 650,
      650, 650, 650, 650, 650, 650, 650, 650, 650, 650,
      650, 650, 650, 650, 650, 650, 650, 650, 650, 650,
      650, 650, 650, 650, 650, 169,   4, 185,  78, 255,
      650,  79,  60, 134,  63, 200, 154,   0,  54, 239,
       29, 650,  88,   5, 100,  40, 100,  85,  90, 250,
      170, 650, 650, 650, 650, 650, 650,  10, 135,  44,
       15, 180, 240,  60, 230,  25, 155,  24,  20,  14,
        5,   5, 200,   0,   0, 170,  70,  40, 155, 134,
       80,   4,  30, 650, 650, 650, 650, 650, 650, 650,
      650, 650, 650, 650, 650, 650, 650, 650, 650, 650,
      650, 650, 650, 650, 650, 650, 650, 650, 650, 650,
      650, 650, 650, 650, 650, 650, 650, 650, 650, 650,
      650, 650, 650, 650, 650, 650, 650, 650, 650, 650,
      650, 650, 650, 650, 650, 650, 650, 650, 650, 650,
      650, 650, 650, 650, 650, 650, 650, 650, 650, 650,
      650, 650, 650, 650, 650, 650, 650, 650, 650, 650,
      650, 650, 650, 650, 650, 650, 650, 650, 650, 650,
      650, 650, 650, 650, 650, 650, 650, 650, 650, 650,
      650, 650, 650, 650, 650, 650, 650, 650, 650, 650,
      650, 650, 650, 650, 650, 650, 650, 650, 650, 650,
      650, 650, 650, 650, 650, 650, 650, 650, 650, 650,
      650, 650, 650, 650, 650, 650
    };
  (void) len;
  return asso_values[(unsigned char)str[3]] + asso_values[(unsigned char)str[2]] + asso_values[(unsigned char)str[1]] + asso_values[(unsigned char)str[0]];
}

const char *
txi_in_language_scripts (register const char *str, register size_t len)
{
  static const char * wordlist[] =
    {
      "", "", "", "", "", "", "", "", "",
      "",
      "Mroo",
      "", "", "",
      "Syrn",
      "Moon",
      "", "",
      "Mymr",
      "Soyo",
      "Sora",
      "", "", "",
      "Maya",
      "Sara",
      "", "", "",
      "Samr",
      "Mand",
      "", "", "",
      "Sylo",
      "", "", "",
      "Mlym",
      "Brai",
      "Mani",
      "", "", "",
      "Maka",
      "Modi",
      "", "", "", "",
      "Sind",
      "", "",
      "Syrc",
      "Marc",
      "Saur",
      "", "", "",
      "Bali",
      "Sidd",
      "", "", "",
      "Plrd",
      "Sund",
      "", "",
      "Bamu",
      "Piqd",
      "Mong",
      "", "",
      "Palm",
      "",
      "Sogo",
      "", "", "", "",
      "Hano",
      "", "", "",
      "Nand",
      "Sogd",
      "", "",
      "Nkoo",
      "",
      "Sunu",
      "",
      "Jamo",
      "",
      "Gran",
      "Hira",
      "", "",
      "Roro",
      "Gara",
      "Hani",
      "", "",
      "Gonm",
      "",
      "Wara",
      "", "",
      "Batk",
      "",
      "Ugar",
      "", "", "", "",
      "Sidt",
      "", "",
      "Pcun",
      "Tayo",
      "Todr",
      "", "",
      "Pauc",
      "Prti",
      "", "", "", "",
      "Bugi",
      "Mult",
      "", "",
      "Runr",
      "Takr",
      "Hang",
      "",
      "Diak",
      "Nagm",
      "Hmng",
      "Hatr",
      "", "",
      "Dogr",
      "Taml",
      "Hant",
      "",
      "Jurc",
      "",
      "Gong",
      "Sarb",
      "", "", "",
      "Hrkt",
      "Hntl",
      "", "", "",
      "Guru",
      "Vaii",
      "", "", "",
      "Syrj",
      "Hung",
      "", "", "",
      "Glag",
      "Talu",
      "", "", "",
      "Laoo",
      "Tang",
      "", "", "",
      "Lana",
      "Toto",
      "",
      "Zyyy",
      "Loma",
      "Aran",
      "Mero",
      "", "",
      "Armn",
      "Syre",
      "", "", "", "",
      "Lina",
      "", "", "",
      "Lydi",
      "Narb",
      "Mend",
      "", "", "",
      "Sgnw",
      "", "", "",
      "Armi",
      "Cyrl",
      "Hanb",
      "", "", "",
      "Bopo",
      "Seal",
      "", "",
      "Adlm",
      "Blis",
      "Cari",
      "", "",
      "Perm",
      "Merc",
      "Kana",
      "",
      "Lyci",
      "Nkdb",
      "Psin",
      "Knda",
      "", "",
      "Cakm",
      "Ital",
      "Krai",
      "", "",
      "Java",
      "Latn",
      "Tglg",
      "", "",
      "Pelm",
      "Brah",
      "Hans",
      "", "", "",
      "Beng",
      "Shrd",
      "", "",
      "Orya",
      "Hluw",
      "Kali",
      "", "",
      "Ranj",
      "Onao",
      "Zzzz",
      "", "", "",
      "Geor",
      "Sinh",
      "", "", "",
      "Nbat",
      "Tutg",
      "", "",
      "Nkgb",
      "Gujr",
      "Mtei",
      "", "",
      "Jpan",
      "Hmnp",
      "Cirt",
      "", "",
      "Grek",
      "",
      "Tnsa",
      "", "",
      "Geok",
      "Buhd",
      "Wole",
      "", "",
      "Elym",
      "Latg",
      "Tols",
      "", "", "", "",
      "Shui",
      "", "", "",
      "Phli",
      "Tagb",
      "", "",
      "Rjng",
      "",
      "Tale",
      "", "", "",
      "Arab",
      "Kitl",
      "", "",
      "Dsrt",
      "Linb",
      "Zanb",
      "", "",
      "Ogam",
      "Inds",
      "Yiii",
      "",
      "Olck",
      "Limb",
      "Phag",
      "Tibt",
      "", "", "",
      "Egyd",
      "Tavt",
      "", "",
      "Dupl",
      "Ougr",
      "Telu",
      "", "", "",
      "Phnx",
      "Teng",
      "", "", "", "",
      "Thaa",
      "", "", "",
      "Bass",
      "Tirh",
      "", "",
      "Zsym",
      "Cyrs",
      "", "", "", "",
      "Wcho",
      "Thai",
      "", "", "",
      "Kawi",
      "Cans",
      "", "",
      "Gukh",
      "",
      "Hebr",
      "", "",
      "Newa",
      "Shaw",
      "Xsux",
      "", "",
      "Rohg",
      "Goth",
      "Kore",
      "", "", "",
      "Lisu",
      "", "", "", "", "",
      "Mahj",
      "", "", "", "", "", "", "", "",
      "Cpmn",
      "Tfng",
      "", "", "", "",
      "Zxxx",
      "", "", "", "", "", "", "",
      "Ahom",
      "",
      "Elba",
      "", "",
      "Deva",
      "Berf",
      "Vith",
      "", "",
      "Bhks",
      "",
      "Zinh",
      "", "",
      "Osma",
      "Phlv",
      "Medf",
      "", "", "",
      "Cham",
      "Khar",
      "", "",
      "Afak",
      "Khmr",
      "", "", "", "", "", "", "", "", "",
      "",
      "Cprt",
      "", "", "", "",
      "Copt",
      "", "", "", "",
      "Kits",
      "", "", "", "", "", "", "", "",
      "Latf",
      "Xpeo",
      "", "", "",
      "Phlp",
      "", "", "", "",
      "Zmth",
      "Yezi",
      "", "", "", "", "", "", "",
      "Orkh",
      "Nshu",
      "Visp",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "Egyp",
      "", "", "", "",
      "Zsye",
      "Kthi",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "Leke",
      "", "", "", "", "", "", "", "", "",
      "",
      "Egyh",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "Avst",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "Lepc",
      "",
      "Ethi",
      "", "", "", "",
      "Chrs",
      "", "", "", "",
      "Khoj",
      "", "", "",
      "Aghb",
      "Cher",
      "", "", "", "",
      "Kpel",
      "", "", "", "", "", "", "", "", "",
      "Chis",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "Osge"
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register unsigned int key = hash (str, len);

      if (key <= MAX_HASH_VALUE)
        {
          register const char *s = wordlist[key];

          if (*str == *s && !strcmp (str + 1, s + 1))
            return s;
        }
    }
  return (const char *) 0;
}
